### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by afdezcl** [afdezcl/kemenu#3]
If you type an URL like [https://kemenu.com/register](url) appear an error:
`This application has no explicit mapping for /error, so you are seeing this as a fallback.`

**Comment by soasada** [comment]
I did the fix in this commit https://github.com/afdezcl/kemenu/commit/72c76e3979ce8ffb6ece8bb9ea88381451e42e98 but I have to check it again because I don't like that the server is sending 404 to these routes. 

A possible solution is to put the path pages one by one in a controller.

**Comment by soasada** [comment]
Also take a look at this:

https://stackoverflow.com/questions/48740997/whitelabel-error-page-404-spring-boot-angular-5
https://stackoverflow.com/questions/44692781/configure-spring-boot-to-redirect-404-to-a-single-page-app
https://stackoverflow.com/questions/43913753/spring-boot-with-redirecting-with-single-page-angular2
